spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: banner.txt
  devtools:
    restart:
      exclude: static/**,public/**,templates/**
sysUser: 史老师
age: 20